name: Test Dask Gateway

on:
  push:
    paths:
      - 'scripts/test_dask.py'
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  test-dask:
    # Falls Pushgateway intern ist, nutze self-hosted statt ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      E2E_ENV: dev               # oder prod; landet als Label in den Metriken
      LOG_DIR: results/logs

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # für den Metrik-Push:
          pip install prometheus-client

      - name: Run Dask Gateway Test
        env:
          EODC_USERNAME: ${{ secrets.EODC_USERNAME }}
          EODC_PASSWORD: ${{ secrets.EODC_PASSWORD }}
        run: |
          python scripts/test_dask.py

      - name: Process logs
        run: |
          python scripts/logs_to_metrics.py

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: results/logs/*.log