name: Test Dask Gateway

on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-dask:
    runs-on:  ubuntu-latest
    timeout-minutes: 30
    env:
      E2E_ENV: dev
      LOG_DIR: results/logs

    steps:
      - name: Check out main with push perms
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install prometheus-client

      - name: Run Dask Gateway Test
        env:
          EODC_USERNAME: ${{ secrets.EODC_USERNAME }}
          EODC_PASSWORD: ${{ secrets.EODC_PASSWORD }}
        run: python scripts/test_dask.py

      # Debug/Check: Logs vorhanden?
      - name: List logs
        if: always()
        run: |
          echo "=== results/logs ==="
          ls -la results/logs || true
          tail -n +1 results/logs/*.log || true

      # Logs → Metriken (Pushgateway)
      - name: Convert logs to metrics (from logs)
        if: always()
        env:
          PUSHGATEWAY_URL: http://localhost:9091/
          E2E_ENV: ${{ env.E2E_ENV }}
          LOG_DIR: ${{ env.LOG_DIR }}
          WINDOW_MINUTES: "60"
        run: python scripts/logs_to_metrics.py

      # Logs als Artefakt (sauberer als ins Repo committen)
      - name: Upload logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}
          path: results/logs/*.log
          if-no-files-found: warn

      - name: Commit and push log files
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --autostash || git reset --hard origin/main 
          git add results/logs/test_DaskGateway.log
          git commit -m "Updated Dask Gateway test logs" || echo "No changes to commit"
          git push
