name: Test Dask Gateway

on:
  push:
    paths:
      - 'scripts/test_dask.py'
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  test-dask:
    # Falls Pushgateway intern ist, nutze self-hosted statt ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 30
    env:
      E2E_ENV: dev               # oder prod; landet als Label in den Metriken
      LOG_DIR: results/logs

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # für den Metrik-Push:
          pip install prometheus-client

      - name: Run Dask Gateway Test
        env:
          EODC_USERNAME: ${{ secrets.EODC_USERNAME }}
          EODC_PASSWORD: ${{ secrets.EODC_PASSWORD }}
        run: |
          python scripts/test_dask.py

      # ⬇️ NEU: Logs → Prometheus-Metriken (Pushgateway)
      - name: Convert logs to metrics (from logs)
        if: always()
        env:
          PUSHGATEWAY_URL: http://localhost:9091   # z.B. http://pushgateway:9091
          E2E_ENV: ${{ env.E2E_ENV }}
          LOG_DIR: ${{ env.LOG_DIR }}
          WINDOW_MINUTES: "60"
        run: |
          python scripts/logs_to_metrics.py

      # Artefakt statt ins Repo committen (sauberer)
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs-${{ github.run_id }}
          path: results/logs/*.log
          retention-days: 7
